#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#Login de usuarios
login:
    path:
        es: /
        en: /en
        zh: /zh
    controller: App\Controller\LoginController::index

#Crear cuentas de usuario
create-account:
    path:
        es: /es/create-account
        en: /en/create-account
        zh: /zh/create-account
    controller: App\Controller\CreateAccountController::index

#Resetear contraseña
forgot-password:
    path:
        es: /es/forgot-password
        en: /en/forgot-password
        zh: /zh/forgot-password
    controller: App\Controller\CreateAccountController::forgotpass

#Activar un usuario ya creado
activate-user:
    path:
        es: /es/activate-user/{token}
        en: /en/activate-user/{token}
        zh: /zh/activate-user/{token}
    controller: App\Controller\CreateAccountController::activate
    requirements:
        token: '.*' #para que sean válidos todos los caracteres

#Estadísticas generales del panel de control
dashboard:
    path:
        es: /es/dashboard
        en: /en/dashboard
        zh: /zh/dashboard
    controller: App\Controller\DashboardController::index

#Editar galería de usuario
user_profile:
    path:
        es: /es/gallery
        en: /en/gallery
        zh: /zh/gallery
    controller: App\Controller\UserProfileController::gallery

#Ajax para actualizar la posición de las imágenes de la galería
update_images_position:
    path:  /gallery/updateImagePosition
    controller: App\Controller\UserProfileController::updateImagePosition
#Ajax para subir imágenes de la galería
upload_image:
    path:  /gallery/uploadImage
    controller: App\Controller\UserProfileController::uploadImage
#Ajax para subir imágenes de la galería
set_favorite_image:
    path:  /gallery/setFavoriteImage
    controller: App\Controller\UserProfileController::setFavoriteImage
#Ajax para subir imágenes de la galería
delete_image:
    path:  /gallery/deleteImage
    controller: App\Controller\UserProfileController::deleteImage


#Editar descripcion de usuario
user_profile_description67:
    path:
        es: /es/description
        en: /en/description
        zh: /zh/description
    controller: App\Controller\UserProfileController::description