#index:
#    path: /
#    controller: App\Controller\DefaultController::index
login:
    path:
        es: /
        es: /acceder
        en: /login
    controller: App\Controller\LoginController::index