#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#Login de usuarios
login:
    path:
        es: /
        en: /en
        zh: /zh
    controller: App\Controller\LoginController::index

#Crear cuentas de usuario
create-account:
    path:
        es: /es/create-account
        en: /en/create-account
        zh: /zh/create-account
    controller: App\Controller\CreateAccountController::index

#Resetear contraseña
forgot-password:
    path:
        es: /es/forgot-password
        en: /en/forgot-password
        zh: /zh/forgot-password
    controller: App\Controller\CreateAccountController::forgotpass

#Activar un usuario ya creado
activate-user:
    path:
        es: /es/activate-user/{token}
        en: /en/activate-user/{token}
        zh: /zh/activate-user/{token}
    controller: App\Controller\CreateAccountController::activate
    requirements:
        token: '.*' #para que sean válidos todos los caracteres

#Estadísticas generales del panel de control
dashboard:
    path:
        es: /es/dashboard
        en: /en/dashboard
        zh: /zh/dashboard
    controller: App\Controller\DashboardController::index

#Editar galería de usuario
user_profile:
    path:
        es: /es/gallery/{profile_id}
        en: /en/gallery/{profile_id}
        zh: /zh/gallery/{profile_id}
    controller: App\Controller\UserProfileController::gallery
    requirements:
        profile_id: '.*' #para que sean válidos todos los caracteres

#Ajax para actualizar la posición de las imágenes de la galería
update_images_position:
    path:  /gallery/updateImagePosition
    controller: App\Controller\UserProfileController::updateImagePosition
#Ajax para subir imágenes de la galería
upload_image:
    path:  /gallery/uploadImage/{profile_id}
    controller: App\Controller\UserProfileController::uploadImage
    requirements:
        profile_id: '.*' #para que sean válidos todos los caracteres
#Ajax para subir imágenes de la galería
set_favorite_image:
    path:  /gallery/setFavoriteImage
    controller: App\Controller\UserProfileController::setFavoriteImage
#Ajax para subir imágenes de la galería
delete_image:
    path:  /gallery/deleteImage/{profile_id}
    controller: App\Controller\UserProfileController::deleteImage
    requirements:
        profile_id: '.*' #para que sean válidos todos los caracteres


#Editar descripcion de usuario
user_profile_description:
    path:
        es: /es/description/{profile_id}
        en: /en/description/{profile_id}
        zh: /zh/description/{profile_id}
    controller: App\Controller\UserProfileController::description
    requirements:
        profile_id: '.*' #para que sean válidos todos los caracteres

#Formas de contacto con el usuario
user_profile_contact:
    path:
        es: /es/contact/{profile_id}
        en: /en/contact/{profile_id}
        zh: /zh/contact/{profile_id}
    controller: App\Controller\UserProfileController::contact
    requirements:
        profile_id: '.*' #para que sean válidos todos los caracteres

#Formas de pago aceptadas por el usuario
user_profile_payment_method:
    path:
        es: /es/payment-method/{profile_id}
        en: /en/payment-method/{profile_id}
        zh: /zh/payment-method/{profile_id}
    controller: App\Controller\UserProfileController::payment_method
    requirements:
        profile_id: '.*' #para que sean válidos todos los caracteres

#Características del usuario
user_profile_about_me:
    path:
        es: /es/about-me/{profile_id}
        en: /en/about-me/{profile_id}
        zh: /zh/about-me/{profile_id}
    controller: App\Controller\UserProfileController::about_me
    requirements:
        profile_id: '.*' #para que sean válidos todos los caracteres

#Nuevo perfil
user_profile_new_profile:
    path:
        es: /es/new-profile
        en: /en/new-profile
        zh: /zh/new-profile
    controller: App\Controller\UserProfileController::new_profile

#Tienda
shop:
    path:
        es: /es/shop
        en: /en/shop
        zh: /zh/shop
    controller: App\Controller\ShopController::home 

#Carrito
cart:
    path:
        es: /es/cart
        en: /en/cart
        zh: /zh/cart
    controller: App\Controller\ShopController::cart    

addToCart:
    path: /cart/add
    controller: App\Controller\ShopController::addToCart  

removeFromCart:
    path: /cart/remove
    controller: App\Controller\ShopController::removeFromCart  

#PayPAl
paypal:
    path: /payment
    controller: App\Controller\PayPalController::main
paypal_ok:
    path: /payment/accepted
    controller: App\Controller\PayPalController::paymentOK
paypal_ko:
    path: /payment/refused
    controller: App\Controller\PayPalController::paymentKO