<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAUxLRyw\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAUxLRyw/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerAUxLRyw.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerAUxLRyw\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerAUxLRyw\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'AUxLRyw',
    'container.build_id' => 'f0247225',
    'container.build_time' => 1541269794,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerAUxLRyw');
