<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8YGbzjt\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8YGbzjt/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container8YGbzjt.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container8YGbzjt\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container8YGbzjt\srcDevDebugProjectContainer(array(
    'container.build_hash' => '8YGbzjt',
    'container.build_id' => '68e50404',
    'container.build_time' => 1540861416,
), __DIR__.\DIRECTORY_SEPARATOR.'Container8YGbzjt');
