<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQbuZutq\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQbuZutq/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQbuZutq.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQbuZutq\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerQbuZutq\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'QbuZutq',
    'container.build_id' => '9605ef6f',
    'container.build_time' => 1540616764,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerQbuZutq');
